import fs from "fs";
import path from "path";
import type { Database } from "../types";

const DB_PATH = path.join(process.cwd(), "data", "db.json");

const db: Database = {
  projects: [
    {
      id: "proj-1",
      name: "Agentic PM App",
      description:
        "A modern project management tool built with AI-native workflows. Kanban boards, backlog management, and team collaboration.",
      key: "PM",
      createdAt: "2025-01-15T10:00:00.000Z",
      updatedAt: "2025-01-20T14:30:00.000Z",
    },
  ],
  teamMembers: [
    {
      id: "user-1",
      name: "Sarah Chen",
      email: "sarah@agenticpm.com",
      avatar: "",
      role: "pm",
    },
    {
      id: "user-2",
      name: "Marcus Johnson",
      email: "marcus@agenticpm.com",
      avatar: "",
      role: "frontend",
    },
    {
      id: "user-3",
      name: "Aisha Patel",
      email: "aisha@agenticpm.com",
      avatar: "",
      role: "backend",
    },
    {
      id: "user-4",
      name: "Tom Wilson",
      email: "tom@agenticpm.com",
      avatar: "",
      role: "design",
    },
    {
      id: "user-5",
      name: "Elena Rodriguez",
      email: "elena@agenticpm.com",
      avatar: "",
      role: "fullstack",
    },
  ],
  labels: [
    { id: "label-1", name: "Bug", color: "#ef4444" },
    { id: "label-2", name: "Feature", color: "#3b82f6" },
    { id: "label-3", name: "Enhancement", color: "#8b5cf6" },
    { id: "label-4", name: "Documentation", color: "#06b6d4" },
    { id: "label-5", name: "Design", color: "#f59e0b" },
    { id: "label-6", name: "Tech Debt", color: "#6b7280" },
  ],
  tasks: [
    {
      id: "task-1",
      projectId: "proj-1",
      title: "Design system color tokens",
      description:
        "Define a consistent set of color tokens for the design system. Include primary, secondary, success, warning, error, and neutral palettes.",
      status: "done",
      priority: "high",
      assigneeId: "user-4",
      labels: ["label-5"],
      storyPoints: 5,
      dueDate: "2025-01-25T00:00:00.000Z",
      order: 0,
      createdAt: "2025-01-15T10:00:00.000Z",
      updatedAt: "2025-01-22T16:00:00.000Z",
    },
    {
      id: "task-2",
      projectId: "proj-1",
      title: "Set up REST API endpoints",
      description:
        "Implement CRUD API routes for projects, tasks, and team members. Use Next.js route handlers with JSON file storage.",
      status: "done",
      priority: "critical",
      assigneeId: "user-3",
      labels: ["label-2"],
      storyPoints: 8,
      dueDate: "2025-01-28T00:00:00.000Z",
      order: 1,
      createdAt: "2025-01-15T11:00:00.000Z",
      updatedAt: "2025-01-26T09:00:00.000Z",
    },
    {
      id: "task-3",
      projectId: "proj-1",
      title: "Implement Kanban board drag-and-drop",
      description:
        "Build the kanban board with @dnd-kit. Support dragging tasks between columns (status changes) and reordering within columns.",
      status: "in_progress",
      priority: "high",
      assigneeId: "user-2",
      labels: ["label-2"],
      storyPoints: 13,
      dueDate: "2025-02-05T00:00:00.000Z",
      order: 0,
      createdAt: "2025-01-16T09:00:00.000Z",
      updatedAt: "2025-01-30T11:00:00.000Z",
    },
    {
      id: "task-4",
      projectId: "proj-1",
      title: "Task detail modal",
      description:
        "Create a modal for viewing and editing task details. Include all fields: title, description, status, priority, assignee, labels, story points, due date.",
      status: "in_progress",
      priority: "medium",
      assigneeId: "user-2",
      labels: ["label-2"],
      storyPoints: 8,
      dueDate: "2025-02-07T00:00:00.000Z",
      order: 1,
      createdAt: "2025-01-16T10:00:00.000Z",
      updatedAt: "2025-01-31T14:00:00.000Z",
    },
    {
      id: "task-5",
      projectId: "proj-1",
      title: "Dashboard analytics charts",
      description:
        "Add bar charts for task status distribution and priority breakdown. Include stats cards for key metrics.",
      status: "in_progress",
      priority: "medium",
      assigneeId: "user-5",
      labels: ["label-2"],
      storyPoints: 8,
      dueDate: "2025-02-10T00:00:00.000Z",
      order: 2,
      createdAt: "2025-01-17T08:00:00.000Z",
      updatedAt: "2025-02-01T10:00:00.000Z",
    },
    {
      id: "task-6",
      projectId: "proj-1",
      title: "Backlog table view with filters",
      description:
        "Implement a table view for the backlog with filtering by status, priority, and assignee. Add sorting by columns.",
      status: "todo",
      priority: "high",
      assigneeId: "user-5",
      labels: ["label-2"],
      storyPoints: 8,
      dueDate: "2025-02-12T00:00:00.000Z",
      order: 0,
      createdAt: "2025-01-17T09:00:00.000Z",
      updatedAt: "2025-01-17T09:00:00.000Z",
    },
    {
      id: "task-7",
      projectId: "proj-1",
      title: "Fix sidebar navigation active state",
      description:
        "The sidebar nav doesn't highlight the currently active page correctly when navigating between projects and team views.",
      status: "todo",
      priority: "low",
      assigneeId: "user-2",
      labels: ["label-1"],
      storyPoints: 2,
      dueDate: "2025-02-14T00:00:00.000Z",
      order: 1,
      createdAt: "2025-01-18T11:00:00.000Z",
      updatedAt: "2025-01-18T11:00:00.000Z",
    },
    {
      id: "task-8",
      projectId: "proj-1",
      title: "Add keyboard shortcuts",
      description:
        "Implement keyboard shortcuts for common actions: N for new task, / for search, Esc to close modals, arrow keys for navigation.",
      status: "todo",
      priority: "low",
      assigneeId: null,
      labels: ["label-3"],
      storyPoints: 5,
      dueDate: null,
      order: 2,
      createdAt: "2025-01-19T14:00:00.000Z",
      updatedAt: "2025-01-19T14:00:00.000Z",
    },
    {
      id: "task-9",
      projectId: "proj-1",
      title: "API rate limiting middleware",
      description:
        "Add rate limiting to API endpoints to prevent abuse. Use a simple in-memory rate limiter with configurable windows.",
      status: "todo",
      priority: "medium",
      assigneeId: "user-3",
      labels: ["label-3", "label-6"],
      storyPoints: 5,
      dueDate: "2025-02-15T00:00:00.000Z",
      order: 3,
      createdAt: "2025-01-20T10:00:00.000Z",
      updatedAt: "2025-01-20T10:00:00.000Z",
    },
    {
      id: "task-10",
      projectId: "proj-1",
      title: "Write API documentation",
      description:
        "Document all REST endpoints with request/response examples. Include curl commands for each endpoint.",
      status: "todo",
      priority: "medium",
      assigneeId: "user-1",
      labels: ["label-4"],
      storyPoints: 3,
      dueDate: "2025-02-18T00:00:00.000Z",
      order: 4,
      createdAt: "2025-01-20T11:00:00.000Z",
      updatedAt: "2025-01-20T11:00:00.000Z",
    },
    {
      id: "task-11",
      projectId: "proj-1",
      title: "Mobile responsive layout",
      description:
        "Ensure the sidebar collapses on mobile, kanban board scrolls horizontally, and forms are usable on small screens.",
      status: "todo",
      priority: "high",
      assigneeId: "user-4",
      labels: ["label-5", "label-3"],
      storyPoints: 8,
      dueDate: "2025-02-20T00:00:00.000Z",
      order: 5,
      createdAt: "2025-01-21T09:00:00.000Z",
      updatedAt: "2025-01-21T09:00:00.000Z",
    },
    {
      id: "task-12",
      projectId: "proj-1",
      title: "Fix task reorder persistence bug",
      description:
        "When dragging tasks to reorder within the same column, the new order is not saved to the database. The order resets on page refresh.",
      status: "in_review",
      priority: "critical",
      assigneeId: "user-3",
      labels: ["label-1"],
      storyPoints: 3,
      dueDate: "2025-02-01T00:00:00.000Z",
      order: 0,
      createdAt: "2025-01-22T15:00:00.000Z",
      updatedAt: "2025-02-01T08:00:00.000Z",
    },
    {
      id: "task-13",
      projectId: "proj-1",
      title: "Refactor database layer to use async/await",
      description:
        "The current db.ts uses synchronous fs operations. Migrate to fs.promises for better performance under load.",
      status: "in_review",
      priority: "medium",
      assigneeId: "user-5",
      labels: ["label-6"],
      storyPoints: 5,
      dueDate: "2025-02-03T00:00:00.000Z",
      order: 1,
      createdAt: "2025-01-23T10:00:00.000Z",
      updatedAt: "2025-02-02T16:00:00.000Z",
    },
    {
      id: "task-14",
      projectId: "proj-1",
      title: "Project creation flow",
      description:
        "Build the create project modal with form validation. Include fields for name, description, and project key. Auto-generate key from name.",
      status: "done",
      priority: "high",
      assigneeId: "user-2",
      labels: ["label-2"],
      storyPoints: 5,
      dueDate: "2025-01-30T00:00:00.000Z",
      order: 2,
      createdAt: "2025-01-16T14:00:00.000Z",
      updatedAt: "2025-01-29T11:00:00.000Z",
    },
    {
      id: "task-15",
      projectId: "proj-1",
      title: "Team workload visualization",
      description:
        "Show each team member's current task count and story point total on the team page. Highlight overloaded members.",
      status: "todo",
      priority: "medium",
      assigneeId: "user-4",
      labels: ["label-2", "label-5"],
      storyPoints: 5,
      dueDate: "2025-02-22T00:00:00.000Z",
      order: 6,
      createdAt: "2025-01-24T09:00:00.000Z",
      updatedAt: "2025-01-24T09:00:00.000Z",
    },
    {
      id: "task-16",
      projectId: "proj-1",
      title: "Dark mode support",
      description:
        "Implement dark mode toggle using CSS variables and next-themes. Ensure all components and charts adapt properly.",
      status: "todo",
      priority: "low",
      assigneeId: null,
      labels: ["label-3", "label-5"],
      storyPoints: 8,
      dueDate: null,
      order: 7,
      createdAt: "2025-01-25T13:00:00.000Z",
      updatedAt: "2025-01-25T13:00:00.000Z",
    },
    {
      id: "task-17",
      projectId: "proj-1",
      title: "Add task comment system",
      description:
        "Allow team members to add comments to tasks. Show comment thread in the task detail modal with timestamps and avatars.",
      status: "done",
      priority: "medium",
      assigneeId: "user-3",
      labels: ["label-2"],
      storyPoints: 8,
      dueDate: "2025-02-01T00:00:00.000Z",
      order: 3,
      createdAt: "2025-01-18T10:00:00.000Z",
      updatedAt: "2025-01-31T15:00:00.000Z",
    },
    {
      id: "task-18",
      projectId: "proj-1",
      title: "Performance audit and optimization",
      description:
        "Run Lighthouse audit, optimize bundle size, add lazy loading for dashboard charts, implement proper loading states.",
      status: "todo",
      priority: "medium",
      assigneeId: "user-5",
      labels: ["label-6", "label-3"],
      storyPoints: 8,
      dueDate: "2025-02-25T00:00:00.000Z",
      order: 8,
      createdAt: "2025-01-26T11:00:00.000Z",
      updatedAt: "2025-01-26T11:00:00.000Z",
    },
  ],
};

// Ensure data directory exists
const dataDir = path.dirname(DB_PATH);
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2), "utf-8");
console.log(`✅ Seed data written to ${DB_PATH}`);
console.log(`   ${db.projects.length} project(s)`);
console.log(`   ${db.teamMembers.length} team member(s)`);
console.log(`   ${db.labels.length} label(s)`);
console.log(`   ${db.tasks.length} task(s)`);
